/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTransferRouteImport } from './routes/_app/transfer'
import { Route as AppStatementRouteImport } from './routes/_app/statement'
import { Route as AppServicesRouteImport } from './routes/_app/services'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppContactRouteImport } from './routes/_app/contact'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTransferRoute = AppTransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => AppRoute,
} as any)
const AppStatementRoute = AppStatementRouteImport.update({
  id: '/statement',
  path: '/statement',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesRoute = AppServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppContactRoute = AppContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/contact': typeof AppContactRoute
  '/dashboard': typeof AppDashboardRoute
  '/services': typeof AppServicesRoute
  '/statement': typeof AppStatementRoute
  '/transfer': typeof AppTransferRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/contact': typeof AppContactRoute
  '/dashboard': typeof AppDashboardRoute
  '/services': typeof AppServicesRoute
  '/statement': typeof AppStatementRoute
  '/transfer': typeof AppTransferRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/contact': typeof AppContactRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/services': typeof AppServicesRoute
  '/_app/statement': typeof AppStatementRoute
  '/_app/transfer': typeof AppTransferRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/signup'
    | '/contact'
    | '/dashboard'
    | '/services'
    | '/statement'
    | '/transfer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/signup'
    | '/contact'
    | '/dashboard'
    | '/services'
    | '/statement'
    | '/transfer'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/admin'
    | '/login'
    | '/signup'
    | '/_app/contact'
    | '/_app/dashboard'
    | '/_app/services'
    | '/_app/statement'
    | '/_app/transfer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/transfer': {
      id: '/_app/transfer'
      path: '/transfer'
      fullPath: '/transfer'
      preLoaderRoute: typeof AppTransferRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/statement': {
      id: '/_app/statement'
      path: '/statement'
      fullPath: '/statement'
      preLoaderRoute: typeof AppStatementRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services': {
      id: '/_app/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AppServicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contact': {
      id: '/_app/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof AppContactRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppContactRoute: typeof AppContactRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppServicesRoute: typeof AppServicesRoute
  AppStatementRoute: typeof AppStatementRoute
  AppTransferRoute: typeof AppTransferRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppContactRoute: AppContactRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppServicesRoute: AppServicesRoute,
  AppStatementRoute: AppStatementRoute,
  AppTransferRoute: AppTransferRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
